spring:
  application:
    name: ecard
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test1?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:mapper/*.xml